#!/bin/bash
cd "${0%/*}"
bash startServer > /dev/null 2>&1

customLength=""
if [ ! -z "${1+x}" ]; 
then 
    customLength=", \"length\":\"$1\"";
fi
curl -d "{\"action\":\"start\"$customLength}" -H "Content-Type: application/json" -X POST http://localhost:55000/pomodoro
echo ""
