#!/bin/bash
if pgrep -x "nodePomodoro" > /dev/null
then
    curl -d '{"action":"stop"}' -H "Content-Type: application/json" -X POST http://localhost:55000/pomodoro
    echo ""
else
    echo "Application not started"
fi